id: PE8486BAC
initial_creation_type: ocr
source_metadata:
  volumes:
    77e64ef8315149ba986eea66cff21528:
      base_file: v071.txt
      image_group_id: I1PD95916
      title: ཆོས་དང་ཆོས་ཉིད་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1683
      volume_number: 71
